{
    'name': 'Purchase Request',
    'summary': 'Purchase Request Module',
    'description': '''To create PR for purchase workflow''',
    'category': 'Custom',
    'version': '0.1',
    'author': 'Your Name',
    'website': 'http://www.yourcompany.co.th',
    'depends': ['base', 'product', 'sale', 'website'],
    'data': [
        'data/project_data.xml',
        'data/group_data.xml',
        'security/ir.model.access.csv',
        'security/security.xml',
        'views/menu.xml',
        'views/project_view.xml',
        'views/pr_view.xml',
        'views/widget_view.xml',
        'views/product_view.xml',
        'views/sale_order_view.xml',
        'views/dashboard_view.xml',
        'wizard/pr_cancel_wizard.xml',
        'wizard/product_wizard.xml',
        'report/pr_form_report.xml',
        'templates/customer_index.xml',
    ],
    'demo': [],
}
